# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 76

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 142

# Offense count: 5
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/pushwoosh.rb'
    - 'lib/pushwoosh/configurable.rb'
    - 'lib/pushwoosh/helpers.rb'
    - 'lib/pushwoosh/push_notification.rb'
    - 'lib/pushwoosh/request.rb'
